### ISSUE TITLE
Action Bar divider not themed on Holo Dark

### ISSUE THREAD

**Issue by MariusVolkhart** [negusoft/holoaccent#12]
The action bar divider when using a transparent action bar with the Holo theme is not styled. 
![screen shot 2014-01-06 at 7 57 45 pm](https://f.cloud.github.com/assets/1709517/1855963/289d2bd2-773f-11e3-8c1c-7a1eb8e46302.png)

**Comment by blurkidi** [comment]
I don't understand the situation you explain:

"using a transparent action bar", the actionbar is transparent. And if you change the background, the divider will be in the color of the background. About "with hte Holo theme", I don't know what you mean, but you have to use the HoloAccent theme.

If you add some implementation detail like code snippets... we might be able to spot the problem, but I don't think that this is a bug.

**Comment by MariusVolkhart** [comment]
Hi, sorry about the vague description.

I took another look, and it was user error. I made the mistake of making Android's Holo theme the parent of my action bar style. As soon as I went back to using HoloAccent as the parent it worked flawlessly. Thanks for responding! I love this library!
