### ISSUE TITLE
Compatibility for API level 10

### ISSUE THREAD

**Issue by ghost** [negusoft/holoaccent#16]
Great idea! If you backport this to API level 10 (with AppCompat) I'd certainly use it in my current project.

**Comment by blurkidi** [comment]
The goal is to eventually backport HoloAccent to older android versionis, this will probably be done as a fork, and based on HoloEverywhere. But first things first, the lib is not finished, and that is the priority at the moment.

**Comment by ghost** [comment]
That was exactly what I wanted to hear, thank you :)
