### ISSUE TITLE
Hard key menu touch feedback

### ISSUE THREAD

**Issue by ghost** [negusoft/holoaccent#17]
I found no way to customize the blue touch feedback in the menu when it's triggered via the hard menu key. Can this library override it?

**Comment by blurkidi** [comment]
I am afraid not. I tried by all means to make it customizable but even with the tricks HoloAccent makes use of, I finally consider it impossible.

**Comment by ghost** [comment]
That makes two of us. Thank you. 
P.S. Maybe you even tried with the floating context menu? Is that the same?

**Comment by blurkidi** [comment]
The [floating context menu](http://developer.android.com/guide/topics/ui/menus.html#FloatingContextMenu) is customizable and it is handled by HoloAccent out of the box.

**Comment by ghost** [comment]
I found [a question on the android developers group](https://groups.google.com/forum/?fromgroups=#!topic/android-developers/GY9DFX2H-Bc), [and another one on SO](http://stackoverflow.com/questions/20781998/customize-the-view-of-context-menu-in-android) where the only solution is creating your own AlertDialog. 
Did you styled it via attributes or just done that?
1st option would be awesome :)

**Comment by blurkidi** [comment]
The questions are not about styling the context menu, they want to completely change the layout. So the solution is not to use the context menu, but to use an AlertDialog instead, indeed.

To answer your question, the context dialog styling is done via attributes. For the AlertDialog, you can have a look at how it works in the [HoloAccent Dialogs wiki page](https://github.com/negusoft/holoaccent/wiki/HoloAccent-Dialogs). The tricky part is to change the color of the divider, if you want more info you can check the [Implementation Details wiki page](http://github.com/negusoft/holoaccent/wiki/Implementation-Details) or have a look at the sources.

**Comment by ghost** [comment]
You are right. Thank you for your help. Will check the implementation soon.
