### ISSUE TITLE
Any plan to add sliding side menu? 

### ISSUE THREAD

**Issue by jpmurray** [negusoft/holoaccent#18]
Hi there, quick question : is there any plan of adding the sliding left menu style that we can see more and more everywhere to the App template?

**Comment by blurkidi** [comment]
Hello,

If you are referring to the [navigation drawer](http://developer.android.com/design/patterns/navigation-drawer.html), it is already supported. If you implement it as explained in the [Creating a Navigation Drawer](http://developer.android.com/training/implementing-navigation/nav-drawer.html) guide, the list will be correctly styled.

If you meant something else, please explain more in detail the issue. Cheers.

**Comment by jpmurray** [comment]
Yes, my bad, terminology's just starting to kick in ;-) Got to play with holoaccent this morning, everything seems great, thanks!
