### ISSUE TITLE
Tab TEXT FIELDS: autocomplete doesn't have visual guide

### ISSUE THREAD

**Issue by trietbui85** [negusoft/holoaccent#20]
In HolloAccentSample, tab TEXT FIELDS, guide of autocomplete is not so helpful. Its hint is "autocomplete" but I don't know what kind of autocomplete text is. I must read resource (`string.xml` > `list_items`) to know it's autocomplete of number (from one to thirteen).

I think you should change its hint to "autocomplete (number)", or change data of `list_items` to countries.

BTW, your HoloAccent lib is so great. Just change 1 line of code and my app has new theme. Many thanks.

**Comment by blurkidi** [comment]
Good suggestion, I will take it into account. That screen was mostly developed for testing purpose but it is true that it could be nice to adapt it for "showcase".
I am going to close the issue though since it is not relevant for the library itself.
Thanks for the suggestion!
