### ISSUE TITLE
How to use HoloAccent with ActionBarCompat

### ISSUE THREAD

**Issue by trietbui85** [negusoft/holoaccent#21]
I want to know how to use HoloAccent with ActionBarCompat (or with ActionBarSherlock - but it's deprecated now, so we're safely to ignore it).

To use HoloAccent, all activities must extent `AccentActivity` while ActionBarCompat is `ActionBarActivity`.

I know we can make main activity extends `ActionBarActivity`, then follow guide in https://github.com/negusoft/holoaccent/wiki/Pro-Tips-&-Tricks to theme this activity. Moreover, an ActionBarActivity activity must have theme `Theme.AppCompat`.

But do you have any simpler solution to combine HoloAccent with ActionBarCompat?

**Comment by blurkidi** [comment]
It is nice to know that people read the wiki pages :+1: . What I suggest is that you create a AccentActionBarActivity that extends ActionBarActivity. Apply the configuration as explained in the guide you mentioned and then let all your activities extend AccentActionBarActivity.

You can just copy the AccentActivity implementation and make it extend ActionBarActivity insted of Activity:
https://github.com/negusoft/holoaccent/blob/master/HoloAccent/src/com/negusoft/holoaccent/activity/AccentActivity.java

Let me know how it went.

**Comment by trietbui85** [comment]
Yeah, I see.
However, because to use ActionBarActivity, in AndroidManifest.xml, its theme must extend `Theme.AppCompat` while to use HoloAccent, activity's theme must be `Theme.HoloAccent`.

Of course I can cheat to fix it by change `<style name="Theme.HoloAccent" parent="android:Theme.Holo">` to make its parent is `Theme.HoloAccent` (in `ha__themes.xml`) but it seems a hack instead of good solution

Do you have any idea?

**Comment by blurkidi** [comment]
Correct me if I am wrong, but I think that Theme.AppCompat is only necessary for preICS devices. HoloAccent is minSdkVersion="14" so I think that it should work with the solution we discussed. Did you try it? what is the result?

**Comment by blurkidi** [comment]
I finally tried it myself and indeed, ActionBarActivity requires a "Theme.AppCompat" theme. But I implemented the sample app with FragmentActivity from the support library and it works. Plus, since HoloAccent is available for Android 4.0+ devices, you won't need the ActionBar backwards supports.

So you can try replacing ActionBarActivity by FragmentActivity and use the "normal" actionbar in stead of the "support" actionbar. Please let me know about the result.

**Comment by trietbui85** [comment]
Thank you @blurkidi .

You're right. From Android 4.0, we can use native ActionBar instead ActionBarSherlock or ActionBarCompat. So, because your lib targets Android 4.0+, so it's safely to use native ActionBar.
