### ISSUE TITLE
HoloAccentSample: add AccentSearchView

### ISSUE THREAD

**Issue by trietbui85** [negusoft/holoaccent#22]
I wish you can add a demo of AccentSearchView to HoloAccentSample.

**Comment by blurkidi** [comment]
It is your lucky day, there is already an example in the sample app. You can check the [ListFragment](https://github.com/negusoft/holoaccent/blob/master/HoloAccentExample/src/com/negusoft/holoaccent/example/fragment/ListFragment.java) class and the [list.xml](https://github.com/negusoft/holoaccent/blob/master/HoloAccentExample/res/menu/list.xml) menu resource.

In any case, AccentSearchView extends SearchView and the usage is exactly the same. You can refer to any example available.
