### ISSUE TITLE
Typo: Colorede?

### ISSUE THREAD

**Issue by trietbui85** [negusoft/holoaccent#24]
In the sample, "Theme & color" has these values which I think it's typo:
- ColoredeActionBar
- ColoredeActionBar (Inverse)
- Light.ColoredeActionBar
- Light.ColoredeActionBar (Inverse)

Should it be `ColoredActionBar` instead of `ColoredeActionBar` (an `e` character is redundant)?

**Comment by blurkidi** [comment]
Indeed, it is a pretty shameful typo :) Plus copy-pasting made it appear all over the place. It is now fixed and the new APK has been pushed to the play store.

Thanks for the thumbs up.
