### ISSUE TITLE
Support for ActionBarActivity

### ISSUE THREAD

**Issue by lukcz** [negusoft/holoaccent#25]
It would be great if you could add support for ActionBarActivity and FragmentActivity as a lot of apps (including mine) still uses support library. It shouldn't be a big deal, except need of adding dependency to support library.

**Comment by blurkidi** [comment]
First remember that HoloAccent supports Android 4.0+ (minSdkVersion="14"). This means that you don't need the support implementation of the action bar. So if you are using ActionBarActivity, consider replacing it by FragmentActivity, or even Activity.

About FragmentActivity, it is supported but you will need a AccentActivity-like class that extends FragmentActivity. You can just copy the [AccentFragmentActivity](https://github.com/negusoft/holoaccent/blob/master/HoloAccentExample/src/com/negusoft/holoaccent/example/activity/AccentFragmentActivity.java) implementation from the sample app into your project. And let your activities extend it.

I added an entry in the "Pro tips & tricks" wiki page that explains this.
