### ISSUE TITLE
ColoredActionBar with TitleInverse style

### ISSUE THREAD

**Issue by trietbui85** [negusoft/holoaccent#26]
The `ColoredActionBar` style makes app look great and is really useful when we need to customize app to make it different from default Holo (Dark, Light) theme.

Sometimes I use `ColoredActionBar` with 'Light' theme to make app looks brighter. However, I also want to keep ActionBar title & subtitle is white instead of dark.

So, could you please add a new theme `Light/Dark ColoredActionBar TitleInverse` which make title&subtitle text color is the same as current theme?

**Comment by blurkidi** [comment]
I am not sure what you mean. You can already choose between _Theme.HoloAccent.Light.ColoredActionBar_ and _Theme.HoloAccent.Light.ColoredActionBar.Inverse_ depending on whether you want dark or light text.

About the subtitle, I didn't test it while developing the lib. But I just tried it out and it seems to behave right. It is light when the the title is light and dark when the title is dark. In any case, you can always extend the existing themes to fit your needs, just as you would with the default android themes.
