### ISSUE TITLE
Suport for DialogFragments V4

### ISSUE THREAD

**Issue by alorma** [negusoft/holoaccent#28]

**Comment by blurkidi** [comment]
Could you describe the issue a bit?

DialogFragments are supported by HoloAccent. Just use AccentDialogFragment instead.

**Comment by alorma** [comment]
Just add a SupportAccentDialogFragment, extending it from android.support.v4.DialogFragment, to use it in ActionBarActivity

**Comment by blurkidi** [comment]
I am trying to avoid the dependency to the support library in holoaccent, but it is still compatible though. It is actually not compatible with ActionBarActivity though, you will need to move to FragmentActivity in stead. You can read more about it in the [Support Library section](https://github.com/negusoft/holoaccent/wiki/Pro-Tips-&-Tricks#support-library-actionbaractivity--fragmentactivity).
I just added some info on how to use the DialogFragment implementation from the support library.

**Comment by alorma** [comment]
Ok.. I understand how use it.

But what's case if i'm not using AccentTheme?

I set a theme extending Accent.Holo.Light.DarkActionBar, but not worked for text, only for divider. What's any option to draw title colored too?

**Comment by blurkidi** [comment]
I just tried and the dialog title was correctly colored, and the button touch feedback too. Did you follow the steps to set it up?

In your case, you need to set the theme correctly and the activity that starts the fragment must be a 'AccentFragmentActivity'. Like specified in the [Support Library section](https://github.com/negusoft/holoaccent/wiki/Pro-Tips-&-Tricks#support-library-actionbaractivity--fragmentactivity) in the _Pro Tips & Tricks_ wiki page.

**Comment by alorma** [comment]
Okay now with AccentSupport dialog it works.

It's a bit weird yet, so we need a AccentActivity, Accentialog... but work
