### ISSUE TITLE
Android Studio - Layout preview problem

### ISSUE THREAD

**Issue by SebastianEngel** [negusoft/holoaccent#29]
For a fragment layout that contains a ListView, the layout preview in Android Studio doesn't render anything and tells me:

> Failed to find style 'listViewStyle' in current theme
> (29 similar errors not shown)
> Failed to convert ?textColorHighlight into a ColorStateList
> (12 similar errors not shown)

I'm not sure if the problem is based in holoaccent or in Android Studio. But before using the library the preview rendered fine. If I switch back my theme to inherit from "android:Theme.Holo.Light", preview rendering is fine again.

Any idea?

**Comment by blurkidi** [comment]
In general, HoloAccent doesn't deal very good with layout preview. The reason is that HoloAccent uses a lot of tricks to be able to define the accent color at runtime. I recommend you select a native Holo theme when working with the layout tool.
