### ISSUE TITLE
Gap in EditText on xxhdpi devices

### ISSUE THREAD

**Issue by intrications** [negusoft/holoaccent#3]
A gap appears when an EditText becomes active on xxhdpi devices such as Nexus 5 and the baseline shifts up and down.

![output_eblodr](https://f.cloud.github.com/assets/1798519/1558086/e717a5a8-4f65-11e3-8f0a-74f2122262f0.gif)

**Comment by intrications** [comment]
Thanks for fixing this.

**Comment by blurkidi** [comment]
Thanks for reporting :)
