### ISSUE TITLE
crash on Android L

### ISSUE THREAD

**Issue by dongxuan** [negusoft/holoaccent#31]
Works fine on 4.4 and crash on Android L

Log:

06-28 16:36:41.816: E/AndroidRuntime(9650): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ha__actionbar_item_background.xml from drawable resource ID #0x7f02003a
06-28 16:36:41.816: E/AndroidRuntime(9650):     at android.content.res.Resources.loadDrawableForCookie(Resources.java:2363)
06-28 16:36:41.816: E/AndroidRuntime(9650):     at android.content.res.Resources.loadDrawable(Resources.java:2265)
06-28 16:36:41.816: E/AndroidRuntime(9650):     at android.content.res.TypedArray.getDrawable(TypedArray.java:743)
06-28 16:36:41.816: E/AndroidRuntime(9650):     at android.view.View.<init>(View.java:3693)
06-28 16:36:41.816: E/AndroidRuntime(9650):     at android.view.ViewGroup.<init>(ViewGroup.java:487)
06-28 16:36:41.816: E/AndroidRuntime(9650):     at android.widget.LinearLayout.<init>(LinearLayout.java:200)
06-28 16:36:41.816: E/AndroidRuntime(9650):     at android.widget.LinearLayout.<init>(LinearLayout.java:196)
06-28 16:36:41.816: E/AndroidRuntime(9650):     at android.widget.Li
06-28 16:36:41.820: E/ActivityManager(767): Invalid thumbnail dimensions: 768x768

**Comment by trietbui85** [comment]
@blurkidi I think when initialize `AccentHelper`, we should check if is Android L. If true, then just ignore initialization.

**Comment by trietbui85** [comment]
Hi, any update on this issue?

**Comment by blurkidi** [comment]
I have a branch locally where it works. But some drawables are not correctly colored, I will try to fix the remaining issues and I will push the branch to github.

**Comment by trietbui85** [comment]
Thank you for your update.

**Comment by blurkidi** [comment]
The fixes for Android Lollipop are available in the dev branch. I would wait to test it in an actual device before creating a release.
