### ISSUE TITLE
Colors defined as ?attr/accentColor reference aren't overridden by AccentHelper

### ISSUE THREAD

**Issue by MikolajKakol** [negusoft/holoaccent#37]
I've overridden `getOverrideAccentColor()` and `getOverrideAccentColorDark()` from `AccentActivity` and it works great in most cases. However with layout defineded as:

```
<TextView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="?attr/accentColorDark"
    android:textColor="?attr/accentColor"
    android:text="someText" />
```

Color of text and background is the same as color defined in XML. It's not overridden by AccentHelper, so I'm left with my base color.

I was looking into some internals and colors that are defined in XML as `?attr/accentColor` are not resolved by AccentHelper/AccentResources. Do you have solution for that? Or maybe there is other way to access accent color from XML?

**Comment by blurkidi** [comment]
The solution for setting the background and the textColor is quite different so let's go step by step:
- **textColor**: Indeed, applying the color through the attribute doesn't allow you to override it. It was a known issue in previous versions. The solution is to set the textColor attribute to "@color/ha__accent". This color is actually a reference to the accentColor, so it can be overriden in real time. 
- **background**: The example you posted even crashes for me, it seems like background doesn't accept references, so we will give it an actual drawable. Create an xml file "res/drawable/accent_fill.xml". It will be a shape drawable:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@color/ha__accent_dark" />
</shape>
```

Then assign the "@drawable/accent_fill" value to the background. Your TextView would be:

``` xml
        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@drawable/accent_fill"
            android:textColor="@color/ha__accent"
            android:text="someText" />
```

Let me know if it works.

PS: I think I will create new attributes like '?attr/accentColorReference' and '?attr/accentColorDrawable' to make this easier. Thanks for the inspiration

**Comment by MikolajKakol** [comment]
It works! Thanks! It would be great if you add those attrs and add information about that in wiki. I haven't seen in samples/wiki that I should use @color/ha__accent to reference accent color so that info might help other too.
