### ISSUE TITLE
Accent is defaulting to blue.

### ISSUE THREAD

**Issue by christiancoleman** [negusoft/holoaccent#38]
Hey I'm trying to use HoloAccent and up until a few days ago the accent has been using my custom style, but now it seems to be defaulting to the Android blue.

**Comment by blurkidi** [comment]
Does that mean you solved the problem? If so, please close the issue.

Otherwise you can explain a bit better your situation so that we may help.

**Comment by christiancoleman** [comment]
Basically I'm just wondering why the color in styles.xml is not being used across all my activities.

![image](https://cloud.githubusercontent.com/assets/6051308/4373058/b02a6806-4329-11e4-826c-0a9580be26f3.png) -
^ My viewpager (MainActivity) - the main screen where everything is accessed. (The wrong color)

![image](https://cloud.githubusercontent.com/assets/6051308/4373078/cee933b2-4329-11e4-9bc5-ace0d410b83c.png)
^ This is the color being used in a branched activity. (The correct color)

The MainActivity (the one with the wrong color) I've extended as a FragmentActivity, so I was using the following code to use HoloAccent:

![image](https://cloud.githubusercontent.com/assets/6051308/4372718/ab00143c-4326-11e4-994d-add3f91d8b44.png)

In the styles.xml I have:

![image](https://cloud.githubusercontent.com/assets/6051308/4372713/92c7371a-4326-11e4-8202-fcbbc671f927.png)

I'm using an extended application to store some global variables and use another external image loading library, so here is the code for the importing of the style:

![image](https://cloud.githubusercontent.com/assets/6051308/4372783/3b4d1a4e-4327-11e4-8b06-9634e9656615.png)

The app is using a FragmentPagerAdapter from the v4 support library and the regular action bar (non support v7). Anyways, all activities that branch from this viewpager are using the color I specified in styles.xml, but the viewpager itself is still defaulting to blue.

I've tried to explicitly set the style on the activity itself.

I've tried to change the color and the theme in the styles.xml - interestingly enough all the branched activities are affected by both the color and the parent change, but the viewpager is only affected by the the parent change.

---

Keep in mind this did work at one point and I have no idea what changed....

**Comment by christiancoleman** [comment]
So I ended up using the AccentFragmentActivity found here: https://github.com/negusoft/holoaccent/blob/master/HoloAccentExample/src/com/negusoft/holoaccent/example/activity/AccentFragmentActivity.java

And it started to work again. O__O I'll close this case now.
