### ISSUE TITLE
Unable to build application with dev version 1.0.1

### ISSUE THREAD

**Issue by dokich** [negusoft/holoaccent#39]
unpacked-libs\cnh_library\res\values\values.xml:728: error: Error: No resource found that matches the given name: attr 'android:paddingStart'.

**Comment by blurkidi** [comment]
'android:paddingStart' is available for api levels 17 and higher. What is your target sdk version? Make sure that the value of 'targetSdkVersion' is 17 or higher in your 'build.gradle' file. Ususally, you should set this value to the highest  version you have tested against.

**Comment by dokich** [comment]
my target sdk is 21. Could be the issue that my min version is 14?
Is it possible maybe move api 17 specific stuff inside v17 folder?
